### ISSUE TITLE
custom_bbox ne semble rien faire.

### ISSUE THREAD

**Issue by r0m1CH** [earion68/hass_custom_bbox#1]
Bonjour,

Merci pour ton adaptation.
j'ai suivi ta doc à plusieurs reprises mais je n'arrive pas à avoir des sensors pour ma nouvelle bbox.

L'intégration se lance bien mais je n'ai rien dans mes entités / sensors.
`2023-12-10 14:54:33.544 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration custom_bbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

`"custom_bbox":{"config_flow":false,"integration_type":"hub","iot_class":"local_polling","name":"Bbox"}`

Je ne sais pas trop comment débuger la chose mais je ne trouve rien:
```
logger:
  default: critical
  logs:
    homeassistant.components.automation: error
    homeassistant.components.websocket_api: debug
    custom_components.custom_bbox: debug
```

Mon HA est dans un docker. 
J'ai mis le DNS de ma box pour m'assurer qu'il puisse résoudre mabbox.bytel.fr

Mais aucune idée de ce qui se passse.

Une idée pour moi ?

Merci

**Comment by earion68** [comment]
Normalement, les sensors ne s'ajoutent pas automatiquement. Lorsque l'intégration est active, les appareils du réseau sont ajoutés automatiquement au fichier known_devices.yaml.

Pour activer l'intégration, ajouter la config au configuration.yaml :
```
device_tracker:
- platform: custom_bbox
  host: 192.168.1.1   # j'utilise une IP, pas la DNS, je suis pas certain que la DNS fonctionne
```

Lorsque l'intégration est active, de nouvelles entrées devraient être ajoutées au fichier known_devices.yaml au bout de quelques minutes. 
Par exemple:
```
30_85_a9_3d_e9_89:
  name: 30_85_a9_3d_e9_89 #peut être changé
  mac: 30:85:A9:3D:E9:89
  icon:
  picture:
  track: true     #changer à true pourqu'un sensor soit créé dans Home Assistant
```
